import type { FileNode } from "@/components/file-tree-item";

export const elasticNavbarFiles: FileNode[] = [
  {
    name: "app",
    type: "folder",
    children: [
      {
        name: "about",
        type: "folder",
        children: [
          {
            name: "page.tsx",
            type: "file",
          },
        ],
      },
      {
        name: "projects",
        type: "folder",
        children: [
          {
            name: "page.tsx",
            type: "file",
          },
        ],
      },
      {
        name: "blog",
        type: "folder",
        children: [
          {
            name: "page.tsx",
            type: "file",
          },
        ],
      },
      {
        name: "skills",
        type: "folder",
        children: [
          {
            name: "page.tsx",
            type: "file",
          },
        ],
      },
      {
        name: "contact",
        type: "folder",
        children: [
          {
            name: "page.tsx",
            type: "file",
          },
        ],
      },
      {
        name: "layout.tsx",
        type: "file",
      },
      {
        name: "page.tsx",
        type: "file",
      },
    ],
  },
  {
    name: "components",
    type: "folder",
    children: [
      {
        name: "navbar.tsx",
        type: "file",
      },
      {
        name: "theme-provider.tsx",
        type: "file",
      },
      {
        name: "theme-toggle.tsx",
        type: "file",
      },
    ],
  },
];

export const elasticNavbarCode: Record<
  string,
  { code: string; language: string }
> = {
  "app/layout.tsx": {
    language: "tsx",
    code: `import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={\`\${geistSans.variable} \${geistMono.variable} h-full antialiased\`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute={"class"}
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}`,
  },
  "app/page.tsx": {
    language: "tsx",
    code: `export default function Home() {
  const cards = [
    { title: "Over-engineered", desc: "Why use 5 lines of CSS when you can use a 50MB library?" },
    { title: "Blazing Fast", desc: "It loads so fast you won't even have time to reconsider your life choices." },
  ];

  return (
    <div className="flex flex-col flex-1 items-center justify-center">
      <main className="flex flex-1 w-full max-w-4xl flex-col items-center py-10 px-16 border-x border-dashed text-center">
        <div className="p-2 px-4 border border-dashed rounded text-base text-muted-foreground mb-4 font-normal">
          Status: Currently Procrastinating
        </div>
        <h1 className="text-2xl font-normal underline decoration-dashed underline-offset-8 decoration-lime-500/50">This is the Home Page</h1>
        <p className="mt-6 text-muted-foreground text-lg font-normal max-w-lg leading-relaxed">
          I spent hours on this site just for you to look at a single sentence. I hope you&apos;re happy.
        </p>
        <div className="mt-8 grid grid-cols-1 md:grid-cols-2 gap-4 w-full max-w-xl">
          {cards.map((card, i) => (
            <div key={i} className="p-4 border border-dashed rounded text-left bg-accent/10">
              <p className="text-base font-normal underline decoration-dashed underline-offset-2 decoration-lime-500/30">{card.title}</p>
              <p className="text-base text-muted-foreground mt-2 leading-relaxed">{card.desc}</p>
            </div>
          ))}
        </div>
      </main>
    </div>
  );
}`,
  },
  "components/navbar.tsx": {
    language: "tsx",
    code: `'use client'

import Link from 'next/link'
import ThemeToggle from './theme-toggle'
import { usePathname } from 'next/navigation';
import { cn } from '@/lib/utils';
import { motion } from "motion/react";
import { useState } from 'react';

function Navbar() {
  const links = [
    {
      label: "Home",
      href: "/",
    },
    {
      label: "About",
      href: "/about",
    },
    {
      label: "Projects",
      href: "/projects",
    },
    {
      label: "Blog",
      href: "/blog",
    },
    {
      label: "Skills",
      href: "/skills",
    },
    {
      label: "Contact",
      href: "/contact",
    },
  ];

  const pathname = usePathname();
  const [highlighted, setHighlighted] = useState<string | null>(null);

  return (
    <div className='w-full px-4 py-2 max-w-4xl mx-auto flex items-center justify-between gap-4 border-b border-x border-dashed'>
      <Link href={"/"} className='font-bold text-lg'>
        Something
      </Link>
      <div className='flex items-center gap-4'>
        <nav 
          className='flex items-center justify-center gap-8' 
          onMouseLeave={() => setHighlighted(null)}
        >
          {links.map((link) => {
            const isActive = pathname === link.href;
            const isHighlighted = (highlighted === link.href) || (highlighted === null && pathname === link.href);

            return (
              <Link
                key={link.href}
                href={link.href}
                className={cn(
                  'relative px-3 py-1 rounded-md',
                  isActive
                )}
                onMouseEnter={() => setHighlighted(link.href)}
              >
                {isHighlighted && (
                  <motion.div
                    layoutId="nav-pill"
                    className={cn(
                      'absolute inset-0 rounded-md shadow border border-dashed bg-accent -z-10',
                      isActive ? 'bg-accent/80' : 'bg-accent/40'
                    )}
                    transition={{
                      type: "spring",
                      stiffness: 250,
                      damping: 35,
                      mass: 2
                    }}
                  />
                )}
                <span className='text-sm font-medium'>
                  {link.label}
                </span>
              </Link>
            )
          })}
        </nav>
        <ThemeToggle />
      </div>
    </div>
  )
}

export default Navbar`,
  },
  "components/theme-provider.tsx": {
    language: "tsx",
    code: `"use client"

import * as React from "react"
import { ThemeProvider as NextThemesProvider } from "next-themes"

export function ThemeProvider({
  children,
  ...props
}: React.ComponentProps<typeof NextThemesProvider>) {
  return <NextThemesProvider {...props}>{children}</NextThemesProvider>
}`,
  },
  "components/theme-toggle.tsx": {
    language: "tsx",
    code: `"use client";

import * as React from "react";
import { Moon, Sun } from "lucide-react";
import { useTheme } from "next-themes";
import { motion, AnimatePresence } from "framer-motion";

export function ModeToggle() {
  const { theme, setTheme } = useTheme();
  const [mounted, setMounted] = React.useState(false);

  const toggleTheme = React.useCallback(() => {
    setTheme(theme === "dark" ? "light" : "dark");
    playSound();
  }, [theme, setTheme]);

  // Handle 'D' key shortcut
  React.useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      // Don't toggle if user is typing in an input, textarea, or contentEditable element
      if (
        e.target instanceof HTMLInputElement ||
        e.target instanceof HTMLTextAreaElement ||
        (e.target as HTMLElement).isContentEditable
      ) {
        return;
      }

      if (e.key.toLowerCase() === "d") {
        toggleTheme();
      }
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [toggleTheme]); 

  React.useEffect(() => setMounted(true), []);

  const playSound = () => {
    const audio = new Audio("/sounds/computer-mouse-click.mp3");
    audio.play();
  };

  // Conditional returns MUST come after ALL hooks are called
  if (!mounted) return <div className="h-10 w-10 shrink-0" />;

  return (
    <button
      onClick={toggleTheme}
      className="
        relative flex items-center justify-center cursor-pointer shrink-0
        h-10 w-10 text-slate-800 dark:text-slate-300 rounded-full
        transition-colors duration-300 inset-shadow-xs inset-shadow-slate-500/40 dark:inset-shadow-slate-600 
      "
    >
      <AnimatePresence initial={false} mode="wait">
        {theme === "dark" ? (
          <motion.span
            key="moon"
            initial={{ rotate: -90, opacity: 0, scale: 0 }}
            animate={{ rotate: 0, opacity: 1, scale: 1 }}
            exit={{ rotate: 90, opacity: 0, scale: 0 }}
            transition={{ duration: 0.20, ease: "easeInOut" }}
            className="absolute"
          >
            <Moon className="h-5 w-5" />
          </motion.span>
        ) : (
          <motion.span
            key="sun"
            initial={{ rotate: 90, opacity: 0, scale: 0 }}
            animate={{ rotate: 0, opacity: 1, scale: 1 }}
            exit={{ rotate: -90, opacity: 0, scale: 0 }}
            transition={{ duration: 0.20, ease: "easeInOut" }}
            className="absolute"
          >
            <Sun className="h-5 w-5" />
          </motion.span>
        )}
      </AnimatePresence>
      <span className="sr-only">Toggle theme</span>
    </button>
  );
}`,
  },
  "app/about/page.tsx": {
    language: "tsx",
    code: `export default function AboutPage() {
  const facts = [
    "Once tried to explain a bug as a 'limited time feature'.",
    "My primary coding environment is a dark room and a bag of chips."
  ];

  return (
    <div className="flex flex-col flex-1 items-center justify-center">
      <main className="flex flex-1 w-full max-w-4xl flex-col items-center py-10 px-16 border-x border-dashed text-center">
        <h1 className="text-2xl font-normal italic opacity-80">A Little About Me</h1>
        <p className="mt-6 text-muted-foreground text-lg font-normal max-w-lg leading-relaxed">
          I enjoy taking credit for things I found on Stack Overflow and talking about my passion for learning while actually just binging Netflix.
        </p>
        <div className="mt-10 flex flex-col gap-4 w-full max-w-lg">
           {facts.map((fact, i) => (
             <div key={i} className="p-4 border border-dashed rounded bg-accent/20 text-base text-muted-foreground font-normal">
               &ldquo;{fact}&rdquo;
             </div>
           ))}
        </div>
      </main>
    </div>
  );
}`,
  },
  "app/projects/page.tsx": {
    language: "tsx",
    code: `export default function ProjectsPage() {
  const projects = [
    { name: "Button that does nothing", status: "Finished" },
    { name: "To-do list (Never checked)", status: "Abandoned" },
    { name: "This website", status: "Ongoing Failure" }
  ];

  return (
    <div className="flex flex-col flex-1 items-center justify-center">
      <main className="flex flex-1 w-full max-w-4xl flex-col items-center py-10 px-16 border-x border-dashed text-center">
        <h1 className="text-2xl font-normal tracking-tight">My Many Projects</h1>
        <p className="mt-4 text-muted-foreground text-lg font-normal max-w-lg leading-relaxed">
          Here is a list of all the things I started and immediately forgot about. The list is empty because I haven&apos;t even finished the list itself.
        </p>
        <div className="mt-12 space-y-4 w-full max-w-xl text-left">
           {projects.map((p, i) => (
             <div key={i} className="flex justify-between items-baseline p-4 border-b border-dashed border-border/50">
                <span className="text-base font-normal">{p.name}</span>
                <span className="text-base text-muted-foreground italic  opacity-60 underline decoration-dashed decoration-1 underline-offset-4">{p.status}</span>
             </div>
           ))}
        </div>
      </main>
    </div>
  );
}`,
  },
  "app/skills/page.tsx": {
    language: "tsx",
    code: `export default function SkillsPage() {
  const skills = [
     "Center a div (theoretically)",
     "Use ChatGPT for every line of code",
     "Expert at renaming files until they work"
  ];

  return (
    <div className="flex flex-col flex-1 items-center justify-center">
      <main className="flex flex-1 w-full max-w-4xl flex-col items-center py-10 px-16 border-x border-dashed text-center">
        <h1 className="text-2xl font-normal italic">My Skills</h1>
        <p className="mt-6 text-muted-foreground text-lg font-normal max-w-lg leading-relaxed">
           I&apos;m very good at typing things into search bars and nodding my head pretending to know what a recursive function is.
        </p>
        <div className="mt-10 flex flex-wrap justify-center gap-4 max-w-xl">
           {skills.map((s, i) => (
             <div key={i} className="px-5 py-2 border border-dashed rounded text-base text-muted-foreground font-normal bg-accent/10">
               {s}
             </div>
           ))}
        </div>
      </main>
    </div>
  );
}`,
  },
  "app/contact/page.tsx": {
    language: "tsx",
    code: `export default function ContactPage() {
  return (
    <div className="flex flex-col flex-1 items-center justify-center">
      <main className="flex flex-1 w-full max-w-4xl flex-col items-center py-10 px-16 border-x border-dashed text-center">
        <h1 className="text-2xl font-normal">Get In Touch</h1>
        <p className="mt-6 text-muted-foreground text-lg font-normal max-w-lg leading-relaxed">
          Go ahead and send me an email. I&apos;ll archive it as soon as it lands so my inbox stays clean.
        </p>
        <div className="mt-12 w-full max-w-sm space-y-6">
           <input className="w-full p-4 border-b border-dashed bg-transparent text-base outline-none focus:border-lime-500 transition-colors" placeholder="Your name (or whatever)" />
           <button className="w-full py-4 border border-dashed rounded text-base hover:bg-zinc-100 dark:hover:bg-zinc-900 transition-colors font-medium">
              Toss into the Void
           </button>
        </div>
      </main>
    </div>
  );
}`,
  },
  "app/blog/page.tsx": {
    language: "tsx",
    code: `export default function BlogPage() {
  return (
    <div className="flex flex-col flex-1 items-center justify-center">
      <main className="flex flex-1 w-full max-w-4xl flex-col items-center py-32 px-16 border-x border-dashed">
        <h1 className="text-4xl font-bold tracking-tight">Blog</h1>
        <p className="mt-4 text-muted-foreground text-lg text-center">
          Thoughts on design, development, and the future of web interfaces.
        </p>
      </main>
    </div>
  );
}`,
  },
};
